"""Add show_admin column

Revision ID: 6ab3b07b4a69
Revises: b8689a0e8198
Create Date: 2025-05-12 17:29:19.870808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab3b07b4a69'
down_revision = 'b8689a0e8198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('show_admin')

    # ### end Alembic commands ###
