"""Remove display name and add rank

Revision ID: b8689a0e8198
Revises: cf6db34f8c31
Create Date: 2025-05-12 15:29:10.367482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8689a0e8198'
down_revision = 'cf6db34f8c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.TEXT(), nullable=True))

    with op.batch_alter_table('tournament_results', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
