"""Add rank to TournamentResult

Revision ID: cf25e058610c
Revises: 9397a8d126fd
Create Date: 2025-05-12 16:41:56.694470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf25e058610c'
down_revision = '9397a8d126fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
