"""Add first and last name fields for guests

Revision ID: cf6db34f8c31
Revises: 73fcadd81003
Create Date: 2025-05-10 14:38:59.210241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6db34f8c31'
down_revision = '73fcadd81003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_firstname', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('guest_lastname', sa.Text(), nullable=True))
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.TEXT(), nullable=True))
        batch_op.drop_column('guest_lastname')
        batch_op.drop_column('guest_firstname')

    # ### end Alembic commands ###
