"""Add user game and sorting type

Revision ID: dd599f424a1b
Revises: 6ab3b07b4a69
Create Date: 2025-05-14 13:59:28.720098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd599f424a1b'
down_revision = '6ab3b07b4a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_game_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_top3_sorting', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_top3_sorting')
        batch_op.drop_column('preferred_game_type')

    # ### end Alembic commands ###
